.PHONY: test

ptcd-test-one-fn:
	@clear
	@date
	@echo "----->> ptcvd-test run pytest <<-----"
	python3 -m pytest tests/python_testes_com_dubles/test_books.py::test_consult_book_returns_format_string


ptcd-test:
	@clear
	@date
	@echo "----->> ptcvd-test run pytest <<-----"
	python3 -m pytest --no-cov tests/python_testes_com_dubles/test_books.py
